### ISSUE TITLE
не хватает пробелов между точкой и первой буквой слова

### ISSUE THREAD

**Issue by katecutekitty** [IKIT-Group/Student-Project#1]
![image](https://github.com/IKIT-Group/Student-Project/assets/162359009/477aef45-ac8b-440a-b634-7017ecd53aaf)

**Comment by Efimish** [comment]
Коллега, уделите внимание проблеме! @DmitriyStupin

**Comment by DmitriyStupin** [comment]
> Коллега, уделите внимание проблеме! @DmitriyStupin 

Я уже обсудил этот вопрос, у нас так сделано по дизайну макета
