### ISSUE TITLE
Неправильное закругление card.html

### ISSUE THREAD

**Issue by Efimish** [IKIT-Group/Student-Project#3]
<img width="260" alt="image" src="https://github.com/IKIT-Group/Student-Project/assets/53897307/72f57758-7cae-4352-ab31-afe5ed6e6a3b">

кривовато

Итак, курс дизайна

Если у нас есть прямоугольник №2 в прямоугольнике №1:
- Прямоугольник №2 имеет border radius = 20px
- Расстояние от края прямоугольника №2 до края прямоугольника №1 = 10px,
тогда Прямоугольник №1 должен иметь border radius = 20px + 10px = 30px

![telegram-cloud-photo-size-2-5317021680129923676-y](https://github.com/IKIT-Group/Student-Project/assets/53897307/94c80e89-477d-4a6f-8da5-d9a50b24a8b1)

**Comment by DmitriyStupin** [comment]
Исправлено. Проблема заключалась в том, что изначально в стилях не указал border-radius для карточки и изображения, который был сделан в макете
